# Site settings
title: D Philhower Studio
email: dphilhowerstudio@gmail.com
description: >-
  D Philhower Studio — logo design, poster design, print media, and website design.
baseurl: ""
url: "https://dphilhowerstudio.com"
