# Site settings
title: dphilhowerstudio
email: hello@dphilhowerstudio.com
description: >-
  Graphic design studio by Dave Philhower — logo design, poster design,
  print media, and website design.
baseurl: ""
url: "https://dphilhowerstudio.com"
twitter_username: WarpedMind01

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "blog/page:num"
