# Site settings
title: D Philhower Studio
email: hello@dphilhowerstudio.com
description: >
  Professional graphic design studio specializing in logo design, poster design,
  print media, and website design. dphilhowerstudio.com
baseurl: ""
url: "https://dphilhowerstudio.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"